.PHONY: dev-up dev-down dev-restart dev-logs

# Команды для локальной разработки
dev-up:
	chmod +x ./deployments/dev-up.sh && ./deployments/dev-up.sh

dev-down:
	chmod +x ./deployments/dev-down.sh && ./deployments/dev-down.sh

dev-restart: dev-down dev-up