# Базовые настройки, приоритет у env файла.
environments:
  development:
    db:
      host: localhost
      port: 5433
      user: postgres
      password: postgres
      name: room_service
    grpc:
      port: 9093 #TODO: для локальной разработки у каждого сервиса свой внешний порт
  production:
    db:
      host: room-db
      port: 5432
      user: postgres
      password: postgres
      name: room_service
    grpc:
      port: 9092