services:
  auth-db:
    image: postgres:16-alpine
    container_name: auth-db-dev
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5431:5432"
    volumes:
      - auth-db-dev-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth_service"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  auth-db-dev-data:
    name: auth-db-dev-data