# Базовые настройки, приоритет у env файла.
db:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  name: booking_service

grpc:
  port: 9092

room_service:
  address: localhost:9093