db:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  name: auth_service

grpc:
  port: 9092

jwt:
  access_token_secret: secret_key_here
  refresh_token_secret: refresh_secret_key_here
  access_token_ttl: 15    # 15 минут
  refresh_token_ttl: 7    # 7 дней