services:
  room-db:
    image: postgres:16-alpine
    container_name: room-db-dev
    environment:
      - POSTGRES_DB=room_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - room-db-dev-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d room_service"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  room-db-dev-data:
    name: room-db-dev-data