services:
  booking-service:
    build:
      context: ../../  #TODO: переделать контекст, когда будет на отдельном сервере или брать образ из реджестери
      dockerfile: booking-service/deployments/Dockerfile
    container_name: booking-service
    ports:
      - "8082:8082" # HTTP port
      - "9092:9092" # gRPC port
    depends_on:
      booking-db:
        condition: service_healthy
    networks:
      - hotel-network
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env:ro

  booking-db:
    image: postgres:16-alpine
    container_name: booking-db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - booking-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - hotel-network
    restart: unless-stopped

volumes:
  booking-db-data:
    name: booking-db-data

networks:
  hotel-network:
    name: hotel-network
    driver: bridge