services:
  booking-db:
    image: postgres:16-alpine
    container_name: booking-db-dev
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - booking-db-dev-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d booking_service"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  booking-db-dev-data:
    name: booking-db-dev-data